#!/bin/sh
# 护栏：禁止 push 到 main / master
# 安装：ln -sf ../../scripts/pre-push .git/hooks/pre-push
while read local_ref local_sha remote_ref remote_sha; do
  case "$remote_ref" in
    refs/heads/master|refs/heads/main)
      echo "⛔ 禁止 push 到 master/main（请推 work / code / build 分支）"
      exit 1 ;;
  esac
done
